export default interface Location {
  id: string;
  name: string;
  lat: number | null;
  lng: number | null;
  distance?: number;
  address: string | null;
  city: string | null;
  zip: string | null;
  phone: string | null;
  phoneExt: string | null;
  startDate: string | null;
  endDate: string | null;
  breakfastStart: string | null;
  breakfastEnd: string | null;
  lunchStart: string | null;
  lunchEnd: string | null;
  snackStart: string | null;
  snackEnd: string | null;
  dinnerStart: string | null;
  dinnerEnd: string | null;
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
  saturday: boolean;
  sunday: boolean;
  servesBreakfast: boolean;
  servesLunch: boolean;
  servesSnack: boolean;
  servesDinner: boolean;
  status?: 'before-start' | 'after-end' | 'open' | 'open-soon' | 'closed';
}
