export default interface Location {
  id: string;
  name: string;
  isMobile: boolean;
  lat: number;
  lng: number;
  distance?: number;
  address: string | null;
  city: string | null;
  zip: string | null;
  website: string;
  notes: string;
  phone: string | null;
  phoneExt: string | null;
  startDate: Date;
  endDate: Date | null;
  breakfastStart: string | null;
  breakfastEnd: string | null;
  lunchStart: string | null;
  lunchEnd: string | null;
  snackStart: string | null;
  snackEnd: string | null;
  dinnerStart: string | null;
  dinnerEnd: string | null;
  currentMeal: 'breakfast' | 'lunch' | 'snack' | 'dinner' | null;
  currentMealUntil: string | null;
  nextMealDate: Date | null;
  monday: boolean;
  tuesday: boolean;
  wednesday: boolean;
  thursday: boolean;
  friday: boolean;
  saturday: boolean;
  sunday: boolean;
  servesBreakfast: boolean;
  servesLunch: boolean;
  servesSnack: boolean;
  servesDinner: boolean;
  status: 'before-start' | 'after-end' | 'open' | 'open-soon' | 'closed-soon' | 'closed';
}
